// <auto-generated />
namespace Varsity_Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class initialmvp : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initialmvp));
        
        string IMigrationMetadata.Id
        {
            get { return "202101221516098_initial-mvp"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
